export default function tmaName() {
  const names = [
    "Sasha James",
    "Sasha James, assistant archivist at the Magnus Institute, London",
    "Martin Blackwood",
    "Martin Blackwood, archival assistant at the Magnus Institute, London",
    "Jonathan Sims, Head Archivist of the Magnus Institute",
    "Johnathan Sims",
    "Melanie King",
    "Adelard Dekker",
    "Agnes Montague",
    "Albrecht von Closen",
    'Alice "Daisy" Tonner',
    "Annabelle Cane",
    "Arthur Nolan",
    "Basira Hussain",
    "Breekon and Hope",
    "Callum Brodie",
    "Daniel Rawlings",
    "Diego Molina",
    "Edwin Burroughs",
    "Elias Bouchard",
    "Eric Delano",
    "Georgie Barker",
    "Gerard Keay",
    "Gertrude Robinson",
    "Gregor Orsinov",
    "Helen Richardson",
    "Jan Kilbride",
    "Jane Prentiss",
    "Jared Hopworth",
    "John Amherst",
    "Jonathan Sims",
    "Jordan Kennedy",
    "Jude Perry",
    "Julia Montauk",
    "Jurgen Leitner",
    "Manuela Dominguez",
    "Mary Keay",
    "Maxwell Rayner",
    "Michael Shelley",
    "Michael Crew",
    "Mikaele Salesa",
    "Natalie Ennis",
    "Neil Lagorio",
    "Nikola Orsinov",
    "Oliver Banks",
    "Peter Lukas",
    "Raymond Fielding",
    "Robert Montauk",
    "Robert Smirke",
    "Rosie Zampano",
    "Sarah Baldwin",
    "Simon Fairchild",
    "The Admiral",
    "Timothy Hodge",
    "Timothy Stoker",
    "Tom Haan",
    "Trevor Herbert",
  ];
  return names[Math.floor(Math.random() * names.length)];
}
